name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

permissions: read-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install trivy and tflint
        run: sudo snap install trivy tflint

      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
